version: '3.8'

services:
  qsm-backend:
    build: .
    container_name: qsm-backend
    ports:
      - "8000:8000"  # Main Application
      - "8001:8001"  # Quantum Service
    environment:
      - AZURE_ENV=production
      - DATABASE_URL=sqlite:////app/data/qms_quantum.db
      - QUANTUM_API_URL=http://localhost:8001
      - ALLOWED_ORIGINS=*
      - JWT_SECRET=your-secure-jwt-secret-here
      - TOKEN_EXPIRE_MINUTES=1440
      - ENABLE_WEBSOCKET=true
    volumes:
      - qsm_data:/app/data
      - qsm_logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  qsm_data:
    driver: local
  qsm_logs:
    driver: local

networks:
  default:
    name: qsm-network