name: Build OQS for Azure

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Build liboqs
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake gcc g++ libssl-dev
        git clone https://github.com/open-quantum-safe/liboqs.git
        cd liboqs && mkdir build && cd build
        cmake -DBUILD_SHARED_LIBS=ON ..
        make -j$(nproc)
        sudo make install
        sudo ldconfig
    
    - name: Build Python package
      run: |
        pip install liboqs
        pip install -r requirements.txt
        
    - name: Create deployment package
      run: |
        tar -czf deployment.tar.gz *
        
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: qsm-backend
        package: deployment.tar.gz